### ISSUE TITLE
Add styling for h1, h2, strong, etc

### ISSUE THREAD

**Issue by jonnyelliot** [commitd/components#128]
The basic html tags don't apply any styling in some cases. For example `<strong>text</strong>` isn't in bold when I think it should be roughly equivalent to `<Text weight="bold">text</Text>`

This is an issue for the markdown rendering in MC https://github.com/commitd/model-cards/issues/106

**Comment by stuarthendren** [comment]
Not sure this is a really components problem.
would be better if the md library converted parts to the components.
We did this in old components for MDX - See https://github.com/commitd/components/blob/main/src/util/mdx.tsx
I think doing the same would be a good solution as we probably need to do this anyway for the blog
