### ISSUE TITLE
Compilation error for variant="primary"

### ISSUE THREAD

**Issue by jonnyelliot** [commitd/components#161]
Setting a variant on a button gives ts error

`<Button variant="tertiary">`

```
Type '{ children: Element; variant: string; }' is not assignable to type 'VariantsCall<{ variant: { brand: any; primary: any; secondary: any; tertiary: any; }; destructive: { false: any; true: any; }; size: { small: any; default: any; large: any; }; force: { hover:
 any; focus: any; active: any; }; }, TMedias & { ...; }>'.
  Types of property 'variant' are incompatible.
    Type 'string' is not assignable to type '"brand" | "primary" | "tertiary" | "secondary" | { [x: string]: "brand" | "primary" | "tertiary" | "secondary" | undefined; initial?: "brand" | "primary" | "tertiary" | "secondary" | undefined; } | undefined'.  TS2322

    16 |   return (
    17 |     <Tooltip content={description} multiline>
  > 18 |       <Button variant={"tertiary"}>
```

A workaround is to use "as const":

`<Button variant={"tertiary" as const}>`

**Comment by jonnyelliot** [comment]
I thought this was an issue with an old ts version but we're now on 4.3.4.

**Comment by stuarthendren** [comment]
It is still complied with 4.2 but I don't know if that has anything to do with it.
I don't know why it works in some places but not here. 
The error is technically correct, if all it know is that it is a string then that's the best it can do. but if that is the case here why is it not always the case. 

Will dig in to it.
