### ISSUE TITLE
Snackbar/Toast component?

### ISSUE THREAD

**Issue by jonnyelliot** [commitd/components#188]
For notifications or acknowledgement of an action that otherwise wouldn't have any feedback. Just hit this in MC for a form that doesnt have any immediate change in the ui when submitted.

**Comment by stuarthendren** [comment]
Yeah, I think this will be added to the Alert, or maybe an extension of it. 

There's some nice toast libs but would rather not use them if I can avoid it.

**Comment by stuarthendren** [comment]
https://react-hot-toast.com/docs/use-toaster

**Comment by jonnyelliot** [comment]
Yeah that looks good. I guess that's good enough standalone that we should just use that directly where needed rather than putting it in components?

**Comment by stuarthendren** [comment]
Not sure - I think it could be worth wrapping up so we get Alerts components without having to repeat it in each project.
The lib itself is fairly small and tree shakeable so shouldn't add much to the end products.

**Comment by stuarthendren** [comment]
Toast component has been added - but left open to add an imperative API
