### ISSUE TITLE
Simplify the use of ThemeProvider

### ISSUE THREAD

**Issue by stuarthendren** [commitd/components#58]
The props are complex and difficult to use.
The complexity should be extracted to a separate function and exported separately to the ThemeProvider, The provider should just take full themes.

The api should allow simpler overriding of elements of the theme without having to supply everything. There should be options to override in both themes and separately in the light and the dark. 

Ideas
```
const {light, dark} = createCommittedThemes() // default committed setup
const {light, dark} = createMaterialThemes() // a way to return to near material defaults

// To simply override a single element of both themes use a `common` key - rest deep merged
const const {light, dark} = createCommittedThemes({ common: {fonts: { fontSize: 20 }}})

// To override using default styles
const const {light, dark} = createCommittedThemes({ common: {fonts: (fontDefaults) => ({ ...fontDefaults:  typography: fontDefaults.text }}})

// For different light/dark config use `light` and `dark` keys
const const {light, dark} = createCommittedThemes({light: {}, dark: {}})

```

e.g. Typing

```
export interface ThemeConfig
  fonts?: FontOptions | (fonts: FontOptions) => FontOptions
  palette?: PaletteOptions | (palette: PaletteOptions) => PaletteOptions
  createShape?: ShapeOptions | (shape: ShapeOptions) => ShapeOptions
  createSpacing?: SpacingOptions | (spacing: SpacingOptions) => SpacingOptions
  createTypography?: TypographyOptions | (typography: TypographyOptions, palette: Palette)) => TypographyOptions
  overrides?: Overrides | (overrides: Overrides, palette: Palette) => Overrides
}

export interface ThemesConfig {
  common?: ThemeConfig
  light?: ThemeConfig
  dark?: ThemeConfig
}
```

**Comment by stuarthendren** [comment]
@jonnyelliot could you have a read of this proposal and validate it for me - or suggest further improvement. No need to do it, just check you think this would be a sensible improvement to make.

**Comment by jonnyelliot** [comment]
This seems like a nice improvement.

I guess we will have to be clear what the behaviour is when things are omitted. If createCommittedThemes and createMaterialThemes are always able to deep merge then thats not a problem.

**Comment by stuarthendren** [comment]
see 22720dff170e39f4d806d1ec7301392969dbd964
