### ISSUE TITLE
Yarn2 warning

### ISSUE THREAD

**Issue by chrisflatley** [commitd/components#63]
On build:

```
Module not found: @committed/components tried to access @material-ui/styles, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.
```

This appears to be correct in that `@material-ui/styles` in not a peer dependency but is imported (e.g. in `src/styles/index.ts`).

[Could be more of these but that I only see this first one].

**Comment by stuarthendren** [comment]
I removed it deliberately as it's transitively brought in by the material-ui/core. And occasionally led to the odd situation where you've have two versions and they clash.

**Comment by chrisflatley** [comment]
Closing this. 

Could test future versions through npm7/yarn and yarn2 CI release process.
