### ISSUE TITLE
<Link /> light-mode text is inconsistent

### ISSUE THREAD

**Issue by jonnyelliot** [commitd/components#73]
4.2.0

```
import { Typography } from "@committed/components"
import { Header,  Root } from "@committed/layout"
...

return <Root> <Header> <Typography>{name}</Typography> </Header> </Root>
```

![image](https://user-images.githubusercontent.com/433293/103889146-d961ec80-50dd-11eb-9dca-8bd3756cc6d3.png)
![image](https://user-images.githubusercontent.com/433293/103889160-de26a080-50dd-11eb-8c9f-aacf678485e9.png)

Swapping Typography for Link:

```
import { Link } from "@committed/components"
import { Header,  Root } from "@committed/layout"
...
return <Root> <Header> <Link>{name}</Link> </Header> </Root>
```

![image](https://user-images.githubusercontent.com/433293/103889295-175f1080-50de-11eb-8473-dbd2a0572290.png)
![image](https://user-images.githubusercontent.com/433293/103889308-1c23c480-50de-11eb-839a-5e66ece88e97.png)

ThemeSwitch has the wrong colour in light mode too when in the header:

![image](https://user-images.githubusercontent.com/433293/103889475-6442e700-50de-11eb-82c5-613fec1171f2.png)

**Comment by stuarthendren** [comment]
The theme switch doesn't know if it is in a primary or secondary header, or any where else. So needs to be told what to do via props.

The link might work if it were inside a typography? (As a current work around) but should probably make the header configure it appropriately.

**Comment by stuarthendren** [comment]
The theme switch doesn't know if it is in a primary or secondary header, or any where else. So needs to be told what to do via props.

The link might work if it were inside a typography? (As a current work around) but should probably make the header configure it appropriately.

**Comment by stuarthendren** [comment]
Consider adding specific components such as 
<https://components-extra.netlify.app/components/navbar/>
<https://components-extra.netlify.app/components/footer/>

**Comment by jonnyelliot** [comment]
<Header /> Was setting the correct font color. The issue was that I was overriding it.

The fix was `color="inherit"`

```
import { Link } from "@committed/components"
import { Header,  Root } from "@committed/layout"
...
return <Root> <Header> <Link color="inherit">{name}</Link> </Header> </Root>
```
